// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wk8igr3xdKLxOCGH3mKm8qxAlt3ZSSo',
    appId: '1:471013851731:web:113c039b4ff308810abca6',
    messagingSenderId: '471013851731',
    projectId: 'axisnet-56a4d',
    authDomain: 'axisnet-56a4d.firebaseapp.com',
    storageBucket: 'axisnet-56a4d.appspot.com',
    measurementId: 'G-18ZEEVNS84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL4BbSfnW2s7qwjVczD5wGZmXnEaEcHps',
    appId: '1:471013851731:android:41ffbea3373ed28c0abca6',
    messagingSenderId: '471013851731',
    projectId: 'axisnet-56a4d',
    storageBucket: 'axisnet-56a4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCayeWqGTSlEJTB6bJpzJMPZuXEDoOAWS8',
    appId: '1:471013851731:ios:0a0c6b9d5778eaa20abca6',
    messagingSenderId: '471013851731',
    projectId: 'axisnet-56a4d',
    storageBucket: 'axisnet-56a4d.appspot.com',
    iosBundleId: 'com.example.tugasUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCayeWqGTSlEJTB6bJpzJMPZuXEDoOAWS8',
    appId: '1:471013851731:ios:0a0c6b9d5778eaa20abca6',
    messagingSenderId: '471013851731',
    projectId: 'axisnet-56a4d',
    storageBucket: 'axisnet-56a4d.appspot.com',
    iosBundleId: 'com.example.tugasUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6wk8igr3xdKLxOCGH3mKm8qxAlt3ZSSo',
    appId: '1:471013851731:web:2813a30a40536a180abca6',
    messagingSenderId: '471013851731',
    projectId: 'axisnet-56a4d',
    authDomain: 'axisnet-56a4d.firebaseapp.com',
    storageBucket: 'axisnet-56a4d.appspot.com',
    measurementId: 'G-X9MHZ0TVTX',
  );

}